"""
Daily Brief Generator (7J)
Standalone entry point that runs the CRO agent to generate today's
Daily Intelligence Brief. Can be called independently of the full pipeline.

Also produces a Markdown export of the brief.
"""

from __future__ import annotations

import sys, os, json
from datetime import date
from pathlib import Path

backend_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if backend_dir not in sys.path:
    sys.path.insert(0, backend_dir)

from aqrti.database.session import get_db_session
from aqrti.database.models import ResearchBrief
from aqrti.utils.logger import get_logger

log = get_logger("daily_brief_generator")

BRIEFS_DIR = Path(backend_dir) / "data" / "briefs"


def _safe_json(s):
    try:
        return json.loads(s) if s else []
    except Exception:
        return []


def get_today_brief(db) -> dict | None:
    row = (
        db.query(ResearchBrief)
        .filter(ResearchBrief.brief_date == date.today())
        .first()
    )
    if not row:
        return None
    return _brief_to_dict(row)


def get_brief_by_date(db, brief_date: date) -> dict | None:
    row = db.query(ResearchBrief).filter(ResearchBrief.brief_date == brief_date).first()
    return _brief_to_dict(row) if row else None


def list_briefs(db, limit: int = 30) -> list[dict]:
    rows = (
        db.query(ResearchBrief)
        .order_by(ResearchBrief.brief_date.desc())
        .limit(limit)
        .all()
    )
    return [_brief_to_dict(r) for r in rows]


def generate_daily_brief() -> dict:
    """
    Run the CRO agent to produce today's brief.
    Returns the brief dict.
    """
    from agents.cro_agent import CROAgent
    with get_db_session() as db:
        agent    = CROAgent()
        findings = agent.execute(db)
        brief    = get_today_brief(db)
        if brief:
            _export_markdown(brief)
        return brief or {"error": "Brief generation failed", "findings": findings}


def _brief_to_dict(row: ResearchBrief) -> dict:
    return {
        "id":                  row.id,
        "brief_date":          str(row.brief_date),
        "title":               row.title,
        "market_summary":      row.market_summary,
        "top_opportunities":   _safe_json(row.top_opportunities),
        "major_risks":         _safe_json(row.major_risks),
        "model_insights":      _safe_json(row.model_insights),
        "strategy_insights":   _safe_json(row.strategy_insights),
        "research_findings":   _safe_json(row.research_findings),
        "lessons_learned":     _safe_json(row.lessons_learned),
        "action_items":        _safe_json(row.action_items),
        "regime_at":           row.regime_at,
        "knowledge_score":     row.knowledge_score,
        "agent_reports_used":  _safe_json(row.agent_reports_used),
        "created_at":          row.created_at.isoformat() if row.created_at else None,
    }


def _export_markdown(brief: dict) -> str:
    """Write brief to a dated Markdown file."""
    BRIEFS_DIR.mkdir(parents=True, exist_ok=True)
    fname = BRIEFS_DIR / f"daily_brief_{brief['brief_date']}.md"

    def ul(items):
        return "\n".join(f"- {i}" for i in items) if items else "_None_"

    lines = [
        f"# AQRTI Daily Intelligence Brief — {brief['brief_date']}",
        f"**Regime:** {brief['regime_at']}  |  **Knowledge Score:** {brief['knowledge_score']}",
        "",
        "## Market Summary",
        brief["market_summary"] or "_No data_",
        "",
        "## Top Opportunities",
        ul(brief["top_opportunities"]),
        "",
        "## Major Risks",
        ul(brief["major_risks"]),
        "",
        "## Model Insights",
        ul(brief["model_insights"]),
        "",
        "## Strategy Insights",
        ul(brief["strategy_insights"]),
        "",
        "## Research Findings",
        ul(brief["research_findings"]),
        "",
        "## Lessons Learned",
        ul(brief["lessons_learned"]),
        "",
        "## Action Items (Human Review Required)",
        ul(brief["action_items"]),
        "",
        f"---",
        f"_Generated by AQRTI CRO Agent at {brief['created_at']}_",
    ]
    fname.write_text("\n".join(lines), encoding="utf-8")
    log.info("Brief exported to %s", fname)
    return str(fname)
